{% set name = "vaex-astro" %}
{% set version = "0.2.0" %}
{% set sha256 = "5c351600388de208bedb3383ef1f2ebf15239d39a862aef916fdb0368f1f85f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - vaex-core >=0.1
    - kapteyn  # [not win]

test:
  imports:
    - vaex.astro

about:
  home: https://www.github.com/maartenbreddels/vaex
  doc_url: https://docs.vaex.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Astronomy related transformations and FITS file support for vaex

extra:
  recipe-maintainers:
    - maartenbreddels
