appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HyH34KDh5dB0KxoaM8NlkiNVw4b9apF/7n7HzwPasNU8rL726vEzVNFjWsp+OvPuwjkS4/NtOWAO8jcrbJrFpBv+kZ5hJ5sguJPL01keW3wcG3fzNthDPsf8LIp8J/yDIQqnHetcqiqGsbC8NUzhITE/68Ec0yY0u5z6rMOER4LY+Is95SyE4R15PoJiltEFvtCtMqVZYzl0mj9VB5MHmHcD8jOMNBY5qhY1UZ+qhoHLCW0lAVLf4WOxcp9hFBC4PNhSitZfqt9xc/easESSjQ05jkZKdMtpWXWdvjhP025Wund6LLBD7Zo2ydNqjEM6HsH5e15DPKd9ZG+O687OBqiDWPNjLaho2UMuYOktTZDqWzbQCZPcIjD8qGVcGNy/mWU3Knpg7GBKFF+tBfhGaekJ0s+TMRoxO2m1QdolZqmF2rrSzbwDK5oJSIL5tKkRF0fdwgPJyMTtfolCBnNrepz+NV9HK52ZwFw3YfKM3j8plARBe29KUr5lURkDDminFTWICkIOwwT/TLMKahXg2Za78HLFYPEyQrNvPU4puXxYfaLUaEg+M+jS9SjxYfeyi68j8WLJAQ3THOtMrDejd/qj+PIICCdN49DKXPqi4pbECV+klkie4O+WjZXGdFBh/0Qjq/VX8t12eZADbf4yxP1Wu4c57gDtZGXPtaH+2pI=}
